class transitionManager{
    constructor(layer,operation){
        this.layer=layer
        this.operation=operation
        this.trigger=false
        this.anim=0
        this.scene=''
        this.control={}
    }
    begin(scene,control){
        this.scene=scene
        this.control=control
        this.trigger=true
    }
    display(scene){
        switch(scene){
            default:
                this.layer.noStroke()
                this.layer.fill(0)
                this.layer.rect(this.anim*this.layer.width/4,this.layer.height/2,this.anim*this.layer.width/2,this.layer.height)
                this.layer.rect(this.layer.width-this.anim*this.layer.width/4,this.layer.height/2,this.anim*this.layer.width/2,this.layer.height)
                this.layer.rect(this.layer.width/2,this.anim*this.layer.height/4,this.layer.width,this.anim*this.layer.height/2)
                this.layer.rect(this.layer.width/2,this.layer.height-this.anim*this.layer.height/4,this.layer.width,this.anim*this.layer.height/2)
            break
        }
    }
    update(){
        if(this.trigger){
            this.anim=round(this.anim*10+1)/10
            if(this.anim>=1){
                this.trigger=false
                this.operation.setup(this.scene,this.control)
            }
        }
        else if(this.anim>0){
            this.anim=round(this.anim*10-1)/10
        }
    }
}